import { InputJsonValue } from "../../types";
import { HubitusUpdateManyWithoutUsersInput } from "./HubitusUpdateManyWithoutUsersInput";
import { StatusUpdateManyWithoutUsersInput } from "./StatusUpdateManyWithoutUsersInput";
import { MessageUpdateManyWithoutUsersInput } from "./MessageUpdateManyWithoutUsersInput";
import { UsepointUpdateManyWithoutUsersInput } from "./UsepointUpdateManyWithoutUsersInput";
import { GetpointUpdateManyWithoutUsersInput } from "./GetpointUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  creatTime?: Date;
  lastLoginTime?: Date;
  username?: string;
  password?: string;
  roles?: InputJsonValue;
  oauthType?: string;
  openId?: string;
  sessionKey?: string | null;
  unionId?: string;
  inviterId?: string | null;
  phone?: string | null;
  trueName?: string | null;
  nickName?: string | null;
  avatarUrl?: string | null;
  gender?: "Unknown" | "Male" | "Female" | null;
  birthday?: Date | null;
  userIdCard?: string | null;
  country?: string | null;
  province?: string | null;
  city?: string | null;
  language?: string | null;
  hubituses?: HubitusUpdateManyWithoutUsersInput;
  Statuses?: StatusUpdateManyWithoutUsersInput;
  messages?: MessageUpdateManyWithoutUsersInput;
  usepoints?: UsepointUpdateManyWithoutUsersInput;
  getpoints?: GetpointUpdateManyWithoutUsersInput;
};
