import { HubitusCheckupCreateNestedManyWithoutUsersInput } from "./HubitusCheckupCreateNestedManyWithoutUsersInput";
import { MessageNotifyCreateNestedManyWithoutUsersInput } from "./MessageNotifyCreateNestedManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { UserStatusCreateNestedManyWithoutUsersInput } from "./UserStatusCreateNestedManyWithoutUsersInput";

export type UserCreateInput = {
  avatarUrl?: string | null;
  birthday?: Date | null;
  city?: string | null;
  country?: string | null;
  creatTime: Date;
  gender?: "Unknown" | "Male" | "Female" | null;
  hubitusCheckups?: HubitusCheckupCreateNestedManyWithoutUsersInput;
  inviterId?: string | null;
  language?: string | null;
  lastLoginTime: Date;
  messageNotifies?: MessageNotifyCreateNestedManyWithoutUsersInput;
  nickName?: string | null;
  oauthType: string;
  openId: string;
  password: string;
  phone?: string | null;
  province?: string | null;
  roles: InputJsonValue;
  sessionKey: string;
  trueName?: string | null;
  unionId: string;
  userIdCard?: string | null;
  username: string;
  userStatuses?: UserStatusCreateNestedManyWithoutUsersInput;
};
