import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { HubitusListRelationFilter } from "../hubitus/HubitusListRelationFilter";
import { StatusListRelationFilter } from "../status/StatusListRelationFilter";
import { MessageListRelationFilter } from "../message/MessageListRelationFilter";
import { QuestionListRelationFilter } from "../question/QuestionListRelationFilter";
import { ReplyListRelationFilter } from "../reply/ReplyListRelationFilter";
import { UsepointListRelationFilter } from "../usepoint/UsepointListRelationFilter";
import { GetpointListRelationFilter } from "../getpoint/GetpointListRelationFilter";

export type UserWhereInput = {
  id?: StringFilter;
  username?: StringFilter;
  oauthType?: StringFilter;
  openId?: StringFilter;
  sessionKey?: StringNullableFilter;
  unionId?: StringFilter;
  inviterId?: StringNullableFilter;
  phone?: StringNullableFilter;
  trueName?: StringNullableFilter;
  nickName?: StringNullableFilter;
  avatarUrl?: StringNullableFilter;
  gender?: "Unknown" | "Male" | "Female";
  birthday?: DateTimeNullableFilter;
  userIdCard?: StringNullableFilter;
  country?: StringNullableFilter;
  province?: StringNullableFilter;
  city?: StringNullableFilter;
  language?: StringNullableFilter;
  hubituses?: HubitusListRelationFilter;
  Statuses?: StatusListRelationFilter;
  messages?: MessageListRelationFilter;
  questions?: QuestionListRelationFilter;
  replys?: ReplyListRelationFilter;
  usepoints?: UsepointListRelationFilter;
  getpoints?: GetpointListRelationFilter;
};
