import { JsonValue } from "type-fest";
import { Hubitus } from "../hubitus/Hubitus";
import { Status } from "../status/Status";
import { IncomeMataGas } from "../incomeMataGas/IncomeMataGas";
import { Message } from "../message/Message";
import { ExpenseMataGas } from "../expenseMataGas/ExpenseMataGas";
import { Inquiry } from "../inquiry/Inquiry";

export type User = {
  oauthType: string;
  nickName: string | null;
  openId: string;
  sessionKey: string | null;
  unionId: string;
  inviterId: string | null;
  phone: string | null;
  gender?: "Unknown" | "Male" | "Female" | null;
  avatarUrl: string | null;
  birthday: Date | null;
  identitycard: string | null;
  country: string | null;
  language: string | null;
  province: string | null;
  city: string | null;
  id: string;
  realName: string | null;
  username: string;
  roles: JsonValue;
  creatTime: Date;
  lastLoginTime: Date;
  hubituses?: Array<Hubitus>;
  statuses?: Array<Status>;
  incomeMataGases?: Array<IncomeMataGas>;
  messages?: Array<Message>;
  expenseMataGases?: Array<ExpenseMataGas>;
  inquirys?: Array<Inquiry>;
};
