import { InputJsonValue } from "../../types";
import { HabitusUpdateManyWithoutUsersInput } from "./HabitusUpdateManyWithoutUsersInput";
import { StatusUpdateManyWithoutUsersInput } from "./StatusUpdateManyWithoutUsersInput";
import { IncomeMetaGasUpdateManyWithoutUsersInput } from "./IncomeMetaGasUpdateManyWithoutUsersInput";
import { MessageUpdateManyWithoutUsersInput } from "./MessageUpdateManyWithoutUsersInput";
import { ExpenseMetaGasUpdateManyWithoutUsersInput } from "./ExpenseMetaGasUpdateManyWithoutUsersInput";
import { InquiryUpdateManyWithoutUsersInput } from "./InquiryUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  oauthType?: string | null;
  nickName?: string | null;
  sessionKey?: string;
  inviterId?: string | null;
  phone?: string | null;
  gender?: "UNKNOWN" | "MALE" | "FEMALE" | null;
  openId?: string;
  avatarUrl?: string | null;
  unionId?: string | null;
  birthday?: Date | null;
  identitycard?: string | null;
  country?: string | null;
  language?: string | null;
  province?: string | null;
  city?: string | null;
  realName?: string | null;
  username?: string;
  password?: string;
  roles?: InputJsonValue;
  creatTime?: Date;
  lastLoginTime?: Date;
  habituses?: HabitusUpdateManyWithoutUsersInput;
  statuses?: StatusUpdateManyWithoutUsersInput;
  incomeMetaGases?: IncomeMetaGasUpdateManyWithoutUsersInput;
  messages?: MessageUpdateManyWithoutUsersInput;
  expenseMetaGases?: ExpenseMetaGasUpdateManyWithoutUsersInput;
  inquirys?: InquiryUpdateManyWithoutUsersInput;
};
