import { InputJsonValue } from "../../types";
import { HubitusCreateNestedManyWithoutUsersInput } from "./HubitusCreateNestedManyWithoutUsersInput";
import { StatusCreateNestedManyWithoutUsersInput } from "./StatusCreateNestedManyWithoutUsersInput";
import { GetpointCreateNestedManyWithoutUsersInput } from "./GetpointCreateNestedManyWithoutUsersInput";
import { UsepointCreateNestedManyWithoutUsersInput } from "./UsepointCreateNestedManyWithoutUsersInput";
import { MessageCreateNestedManyWithoutUsersInput } from "./MessageCreateNestedManyWithoutUsersInput";
import { QuestionCreateNestedManyWithoutUsersInput } from "./QuestionCreateNestedManyWithoutUsersInput";

export type UserCreateInput = {
  oauthType: string;
  nickName?: string | null;
  openId: string;
  sessionKey?: string | null;
  unionId: string;
  inviterId?: string | null;
  phone?: string | null;
  gender?: "Unknown" | "Male" | "Female" | null;
  avatarUrl?: string | null;
  birthday?: Date | null;
  userIdCard?: string | null;
  country?: string | null;
  language?: string | null;
  province?: string | null;
  city?: string | null;
  realName?: string | null;
  username: string;
  password: string;
  roles: InputJsonValue;
  creatTime: Date;
  lastLoginTime: Date;
  hubituses?: HubitusCreateNestedManyWithoutUsersInput;
  statuses?: StatusCreateNestedManyWithoutUsersInput;
  getpoints?: GetpointCreateNestedManyWithoutUsersInput;
  usepoints?: UsepointCreateNestedManyWithoutUsersInput;
  messages?: MessageCreateNestedManyWithoutUsersInput;
  questions?: QuestionCreateNestedManyWithoutUsersInput;
};
