/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsJSON, ValidateNested } from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UsePointCreateNestedManyWithoutUsersInput } from "./UsePointCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { GetPointCreateNestedManyWithoutUsersInput } from "./GetPointCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UsePointCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UsePointCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UsePointCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  usePoints?: UsePointCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => GetPointCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => GetPointCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => GetPointCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  getPoints?: GetPointCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
