/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateInquiryArgs } from "./CreateInquiryArgs";
import { UpdateInquiryArgs } from "./UpdateInquiryArgs";
import { DeleteInquiryArgs } from "./DeleteInquiryArgs";
import { InquiryFindManyArgs } from "./InquiryFindManyArgs";
import { InquiryFindUniqueArgs } from "./InquiryFindUniqueArgs";
import { Inquiry } from "./Inquiry";
import { User } from "../../user/base/User";
import { InquiryService } from "../inquiry.service";
@graphql.Resolver(() => Inquiry)
export class InquiryResolverBase {
  constructor(protected readonly service: InquiryService) {}

  async _inquiriesMeta(
    @graphql.Args() args: InquiryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Inquiry])
  async inquiries(
    @graphql.Args() args: InquiryFindManyArgs
  ): Promise<Inquiry[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Inquiry, { nullable: true })
  async inquiry(
    @graphql.Args() args: InquiryFindUniqueArgs
  ): Promise<Inquiry | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Inquiry)
  async createInquiry(
    @graphql.Args() args: CreateInquiryArgs
  ): Promise<Inquiry> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Inquiry)
  async updateInquiry(
    @graphql.Args() args: UpdateInquiryArgs
  ): Promise<Inquiry | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Inquiry)
  async deleteInquiry(
    @graphql.Args() args: DeleteInquiryArgs
  ): Promise<Inquiry | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  async user(@graphql.Parent() parent: Inquiry): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
