/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateGetpointArgs } from "./CreateGetpointArgs";
import { UpdateGetpointArgs } from "./UpdateGetpointArgs";
import { DeleteGetpointArgs } from "./DeleteGetpointArgs";
import { GetpointFindManyArgs } from "./GetpointFindManyArgs";
import { GetpointFindUniqueArgs } from "./GetpointFindUniqueArgs";
import { Getpoint } from "./Getpoint";
import { User } from "../../user/base/User";
import { GetpointService } from "../getpoint.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Getpoint)
export class GetpointResolverBase {
  constructor(
    protected readonly service: GetpointService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Getpoint",
    action: "read",
    possession: "any",
  })
  async _getpointsMeta(
    @graphql.Args() args: GetpointFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Getpoint])
  @nestAccessControl.UseRoles({
    resource: "Getpoint",
    action: "read",
    possession: "any",
  })
  async getpoints(
    @graphql.Args() args: GetpointFindManyArgs
  ): Promise<Getpoint[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Getpoint, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Getpoint",
    action: "read",
    possession: "own",
  })
  async getpoint(
    @graphql.Args() args: GetpointFindUniqueArgs
  ): Promise<Getpoint | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Getpoint)
  @nestAccessControl.UseRoles({
    resource: "Getpoint",
    action: "create",
    possession: "any",
  })
  async createGetpoint(
    @graphql.Args() args: CreateGetpointArgs
  ): Promise<Getpoint> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Getpoint)
  @nestAccessControl.UseRoles({
    resource: "Getpoint",
    action: "update",
    possession: "any",
  })
  async updateGetpoint(
    @graphql.Args() args: UpdateGetpointArgs
  ): Promise<Getpoint | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Getpoint)
  @nestAccessControl.UseRoles({
    resource: "Getpoint",
    action: "delete",
    possession: "any",
  })
  async deleteGetpoint(
    @graphql.Args() args: DeleteGetpointArgs
  ): Promise<Getpoint | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async user(@graphql.Parent() parent: Getpoint): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
